name: go_cart
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.5
  cupertino_icons: ^1.0.8
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0

  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0

  build_runner: ^2.4.10
  # isar_generator: ^3.1.0+1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
