name: Build Windows EXEs for main_a and main_b

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build EXE on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build main_a
        run: flutter build windows -t lib/main_a.dart

      - name: Rename main_a.exe
        run: |
          mkdir artifacts
          copy build\windows\x64\runner\Release\go_cart.exe artifacts\main_a.exe

      - name: Clean and build main_b
        run: |
          flutter clean
          flutter pub get
          flutter build windows -t lib/main_b.dart

      - name: Rename main_b.exe
        run: copy build\windows\x64\runner\Release\go_cart.exe artifacts\main_b.exe

      - name: Upload full build folders
        uses: actions/upload-artifact@v4
        with:
          name: windows_exe_full_builds
          path: build/windows/x64/runner/Release/**
