name: Build Multiple Windows App Instances

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Dependencies
        run: flutter pub get

      # Build Instance A
      - name: Build main_a
        run: flutter build windows -t lib/main_a.dart

      - name: Copy Instance A Build Folder
        run: |
          mkdir builds
          xcopy /E /I /Y build\windows\x64\runner\Release builds\instance_a

      # Build Instance B
      - name: Build main_b
        run: flutter build windows -t lib/main_b.dart

      - name: Copy Instance B Build Folder
        run: xcopy /E /I /Y build\windows\x64\runner\Release builds\instance_b

      # Build Instance C
      # - name: Build main_c
      #   run: flutter build windows -t lib/main_c.dart
      #
      # - name: Copy Instance C Build Folder
      #   run: xcopy /E /I /Y build\windows\x64\runner\Release builds\instance_c

      - name: Upload All App Instances
        uses: actions/upload-artifact@v4
        with:
          name: go_cart_windows_instances
          path: builds/
